# Generated by Django 5.2.6 on 2025-09-27 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('dispositivos', '0002_device_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dispositivos.device')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalog.alertrule')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='measurements.measurement')),
            ],
        ),
    ]
