# Generated by Django 5.2.6 on 2025-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('info', 'Informativa'), ('warn', 'Advertencia'), ('crit', 'Crítica')], default='warn', max_length=5),
        ),
    ]
