# Generated by Django 5.2.6 on 2025-09-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('organizations', '0002_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.zone'),
        ),
    ]
